n = str(input('Qual é o seu nome completo?')).strip()
ma = n.upper()
mi = n.lower()
l = len(n)
s = (n.split())
le = len(s[0])
print ('Analisando seu nome...')
print ('O seu nome é {}'.format(n))
print ('Com letra maiúscula fica {}'.format(ma))
print ('Com leta minúscula fica {}'.format(mi))
print ('Seu nome tem ao todo {} letras'.format(l))
#print ('Seu primeiro nome é {} e ele tem {} letras'.format(s[0],le))